modLoader="javafml"
loaderVersion="[32,)" 
issueTrackerURL="https://github.com/MORIMORI0317/YJSNPIMOD/issues"
logoFile="logo.png" 
[[mods]]
modId="yjsnpimod"
version="${file.jarVersion}" 
displayName="The YJSNPI MOD"
updateJSONURL="https://raw.githubusercontent.com/MORIMORI0317/YJSNPIMOD/master/update_check.json" 
displayURL="https://github.com/MORIMORI0317/YJSNPIMOD" 
credits=""
authors="MORIMORI0317" 
description="Thank you for downloading!\nThe Ikisugi MOD."

[[dependencies.kimnarutree]]
    modId="otyacraftengine"
    mandatory=true
    versionRange="[1.0,)"
    ordering="NONE"
    side="BOTH"
